/*It is the header for Matt's ICQ clone with russian words, written by 
Dima Veselov, 2:5030/175.1002. Version 1.3 */

/* Help categories */
#define CLIENT_CAT_STR "Client"
#define MESSAGE_CAT_STR "Message"
#define USER_CAT_STR "User"
#define ACCOUNT_CAT_STR "Account"

/* Help strings for each command */
#define PASS_HELP_STR "\t\tСменить Ваш пароль на секретный.\n"
#define MSG_HELP_STR "\t\tПослать сообщение на uin\n"
#define URL_HELP_STR "\tПослать сообщение и URL на uin\n"
#define MSGA_HELP_STR "\t\tПослать многостроковое сообщение всем .\n\t\t\t\tв контакт-листе.\n"
#define AGAIN_HELP_STR "\t\t\tПослать сообщение последнему человеку, .\n\t\t\t\tкоторому Вы что-то посылали\n"
#define AUTH_HELP_STR "\t\tАвторизировать uin, чтобы он \n\t\t\t\tдобавил Вас в свой контакт-лист\n"
#define REPLY_HELP_STR "\t\t\tОтвет на последнее сообщение\n"
#define RAND_HELP_STR "\t\tНайти случайного человека в указанной(ых) группе(ах).\n"
#define LIST_HELP_STR "\t\t\tПоказать статус всех в Вашем контакт-листе\n"
#define ALTER_HELP_STR "\tОбновить набор комманд на лету.\n"
#define VERBOSE_HELP_STR "\t\t\tУстановить количество вывода на экран .\n\t\t\t\t(по умолчанию 0).\n"
#define CLEAR_HELP_STR "\t\t\t\tОчистить экран.\n"
#define SOUND_HELP_STR "\t\t\t\tОтключить звук во время приема новых сообщений.\n"
#define COLOR_HELP_STR "\t\t\t\tИзменить цвета.\n"
#define QUIT_HELP_STR "\t\t\tОтключится от сервера и выйти из micq\n"
#define AUTO1_HELP_STR "\t\t\t\tПоказать статус автоответчика\n"
#define AUTO2_HELP_STR "\t\t\tПереключить посылку сообщений.\n\t\t\t\tпри статусе DND, NA, и т.д..\n"
#define AUTO3_HELP_STR "\t\tУстановить сообщение, .\n\t\t\t\tкак сообщение автоответчика\n"
#define REG_HELP_STR "\tСоздать UIN с указанным паролем.\n"
#define CHANGE_HELP_STR "\tИзменить статус на другой по номеру.\n\t\tБез указания номера будет выведены номера и соотв. режимы.\n"
#define ADD_HELP_STR "\tДобавить UIN в контакт-лист под именем.\n"
#define SEARCH_HELP_STR "\tИскать пользователя ICQ по e-mail адресу.\n"
#define INFO_HELP_STR "\t\tПоказать информацию по uin\n"
#define ONLINE_HELP_STR "\t\tРежим 'На линии'.\n"
#define AWAY_HELP_STR "\t\tРежим Отошел.\n"
#define NA_HELP_STR "\t\tРежим Не доступен.\n"
#define OCC_HELP_STR "\t\tРежим занят.\n"
#define DND_HELP_STR "\t\tРежим не беспокоить.\n"
#define FFC_HELP_STR "\t\tРежим готов пообщатся.\n"
#define INV_HELP_STR "\t\tРежим невидимости.\n"
#define UPDATE_HELP_STR "\t\tИзменить информацию о Вас на сервере (email, имя, и т.д..)\n"
#define SET_RAND_HELP_STR "\t\tУказать вашу группу для случайных пользователей.\n"

#define VERBOSE_LEVEL_STR "Режим вывода на экран %d.\n"
#define NICK_NOT_FOUND_STR "%s не известен в контакт-листе"

/* Used in the "w" user display */
#define W_ONLINE_SINCE_STR " На линии с %s"
#define W_LAST_ONLINE_STR " Последний раз был на линии %s"
#define W_LAST_ON_UNKNOWN_STR " Последний раз был неизвестно когда."
#define W_STATUS_STR "Ваш статус: "
#define W_OFFLINE_STR "Отсутствующие люди: "
#define W_ONLINE_STR "Люди на линии: "

#define MSG_PROMPT_STR "msg> "
#define MSGA_PROMPT_STR "msg all> "

/* These are used durring user info updates. */
#define NICK_NAME_UPDATE_STR "Ваша новая кличка : "
#define FIRST_NAME_UPDATE_STR "Ваше имя : "
#define LAST_NAME_UPDATE_STR "Ваша фамилия : "
#define EMAIL_UPDATE_STR "Новый e-mail адрес : "
#define AUTH_QUESTION_STR "Требовать авторизации у других пользователей? : "

#define YESNO_RESPONSE_STR "Пожалуйста введите " YES_STR " or " NO_STR "\n"
#define MESSAGE_BUFFER_FULL_STR "Сообщение было послано, когда закончился буфер\n"
#define MESSAGE_CANCELED_STR "Сообщение не послано\n"
/* Having 2 strings with the nickname inserted in the middle */
/* will hopefully solve any potential word order problems */
#define MESSAGE_SENT_1_STR  "Сообщение ушло "
#define MESSAGE_SENT_2_STR  "!\n"

/********************************************************************/
/* Simple Yes no response*/
#define YES_STR "YES"
#define NO_STR "NO"

/* The promt used by Micq */
#define PROMPT_STR SERVCOL "Micq> " NOCOL

/* The different status modes */
#define STATUS_ONLINE_STR "На линии"
#define STATUS_DND_STR "Не беспокоить"
#define STATUS_AWAY_STR "Вышел"
#define STATUS_NA_STR "Не доступен"
#define STATUS_OCCUPIED_STR "Занят"
#define STATUS_INVISIBLE_STR "Невидим"
#define STATUS_FFC_STR "Хочу пообщаться"

/* results of searches */
#define ALL_FOUND_STR "Все пользователи найдены."
#define TOO_MANY_STR "Найдено слишеом много пользователей."
#define SEARCH_DONE_STR "Поиск завершен."

/* Strings for help screen */
#define SELECT_GROUP_STR "Выберите одну из тем."
#define CLIENT_HELP_STR "Команды, относящиеся к дисплею и конфигурации."
#define USER_HELP_STR "Команды, относящиеся к поиску пользователей."
#define ACCOUNT_HELP_STR "Команды, относящиеся к Вашему uin."
#define MESSAGE_HELP_STR "Команды, относящиеся к посылке сообщений."

/* Various Strings */
#define LENGTH_STR "Длина"
#define EXTRA_DATA_STR "Extra Data"
#define SEQ_STR "SEQ"
#define VER_STR "Ver"
#define LOGIN_SUCCESS_STR "Логин на сервер прошел нормально!"
#define SERVER_ACK_STR "Сервер послал Вам команду %04x."

/* The Countries there's alot */
#define USA_COUNTRY_STR "США"
#define Afghanistan_COUNTRY_STR (const char*) "Афганистан"
#define Albania_COUNTRY_STR "Албания"
#define Algeria_COUNTRY_STR "Алжир"
#define American_Samoa_COUNTRY_STR "American Samoa"
#define Andorra_COUNTRY_STR "Андора"
#define Angola_COUNTRY_STR "Ангола"
#define Anguilla_COUNTRY_STR "Анжилла"
#define Antigua_COUNTRY_STR "Antigua"
#define Argentina_COUNTRY_STR "Аргентина"
#define Armenia_COUNTRY_STR "Армения"
#define Aruba_COUNTRY_STR "Аруба"
#define Ascention_Island_COUNTRY_STR "Ascention Island"
#define Australia_COUNTRY_STR "Австралия"
#define Australian_Antartic_Territory_COUNTRY_STR "Австралийская антарктическая территория"
#define Austria_COUNTRY_STR "Австрия"
#define Azerbaijan_COUNTRY_STR "Азербайджан"
#define Bahamas_COUNTRY_STR "Бахамас"
#define Bahrain_COUNTRY_STR "Bahrain"
#define Bangladesh_COUNTRY_STR "Бангладеш"
#define Barbados_COUNTRY_STR "Барбадос"
#define Belarus_COUNTRY_STR "Беларусь"
#define Belgium_COUNTRY_STR "Бельгия"
#define Belize_COUNTRY_STR "Belize"
#define Benin_COUNTRY_STR "Бенин"
#define Bermuda_COUNTRY_STR "Бермуды"
#define Bhutan_COUNTRY_STR "Bhutan"
#define Bolivia_COUNTRY_STR "Боливия"
#define Bosnia_Herzegovina_COUNTRY_STR "Босния и Герцеговина"
#define Botswana_COUNTRY_STR "Botswana"
#define Brazil_COUNTRY_STR "Бразилия"
#define British_Virgin_Islands_COUNTRY_STR "British Virgin Islands"
#define Brunei_COUNTRY_STR "Brunei"
#define Bulgaria_COUNTRY_STR "Болгария"
#define Burkina_Faso_COUNTRY_STR "Burkina Faso"
#define Burundi_COUNTRY_STR "Burundi"
#define Cambodia_COUNTRY_STR "Камбоджи"
#define Cameroon_COUNTRY_STR "Камерун"
#define Canada_COUNTRY_STR "Канада"
#define Cape_Verde_Islands_COUNTRY_STR "Cape Verde Islands"
#define Cayman_Islands_COUNTRY_STR "Cayman Islands"
#define Central_African_Republic_COUNTRY_STR "ЮАР"
#define Chad_COUNTRY_STR "Chad"
#define Christmas_Island_COUNTRY_STR "Christmas Island"
#define Cocos_Keeling_Islands_COUNTRY_STR "Cocos-Keeling Islands"
#define Comoros_COUNTRY_STR "Comoros"
#define Congo_COUNTRY_STR "Конго"
#define Cook_Islands_COUNTRY_STR "Cook Islands"
#define Chile_COUNTRY_STR "Chile"
#define China_COUNTRY_STR "Китай"
#define Columbia_COUNTRY_STR "Колумбия"
#define Costa_Rice_COUNTRY_STR "Costa Rice"
#define Croatia_COUNTRY_STR "Хорватия"
#define Cuba_COUNTRY_STR "Куба"
#define Cyprus_COUNTRY_STR "Кипр"
#define Czech_Republic_COUNTRY_STR "Чешская республика"
#define Denmark_COUNTRY_STR "Denmark"
#define Diego_Garcia_COUNTRY_STR "Diego Garcia"
#define Djibouti_COUNTRY_STR "Djibouti"
#define Dominica_COUNTRY_STR "Dominica"
#define Dominican_Republic_COUNTRY_STR "Dominican Republic"
#define Ecuador_COUNTRY_STR "Ecuador"
#define Egypt_COUNTRY_STR "Египт"
#define El_Salvador_COUNTRY_STR "Сальвадор"
#define Equitorial_Guinea_COUNTRY_STR "Equitorial Guinea"
#define Eritrea_COUNTRY_STR "Eritrea"
#define Estonia_COUNTRY_STR "Эстония"
#define Ethiopia_COUNTRY_STR "Эфиопия"
#define Former_Yugoslavia_COUNTRY_STR "Югославия"
#define Faeroe_Islands_COUNTRY_STR "Faeroe Islands"
#define Falkland_Islands_COUNTRY_STR "Falkland Islands"
#define Federated_States_of_Micronesia_COUNTRY_STR "Federated States of Micronesia"
#define Fiji_COUNTRY_STR "Fiji"
#define Finland_COUNTRY_STR "Финляндия"
#define France_COUNTRY_STR "Франция"
#define French_Antilles_COUNTRY_STR "French Antilles"
#define French_Guiana_COUNTRY_STR "French Guiana"
#define French_Polynesia_COUNTRY_STR "French Polynesia"
#define Gabon_COUNTRY_STR "Gabon"
#define Gambia_COUNTRY_STR "Gambia"
#define Georgia_COUNTRY_STR "Джрджия"
#define Germany_COUNTRY_STR "Германия"
#define Ghana_COUNTRY_STR "Гана"
#define Gibraltar_COUNTRY_STR "Габралтар"
#define Greece_COUNTRY_STR "Греция"
#define Greenland_COUNTRY_STR "Greenland"
#define Grenada_COUNTRY_STR "Grenada"
#define Guadeloupe_COUNTRY_STR "Гваделупа"
#define Guam_COUNTRY_STR "Guam"
#define Guantanomo_Bay_COUNTRY_STR "Guantanomo Bay"
#define Guatemala_COUNTRY_STR "Гватемала"
#define Guinea_COUNTRY_STR "Гвинея"
#define Guinea_Bissau_COUNTRY_STR "Guinea-Bissau"
#define Guyana_COUNTRY_STR "Guyana"
#define Haiti_COUNTRY_STR "Хаити"
#define Honduras_COUNTRY_STR "Гондурас"
#define Hong_Kong_COUNTRY_STR "Гонг Конг"
#define Hungary_COUNTRY_STR "Венгрия"
#define Iceland_COUNTRY_STR "Исландия"
#define India_COUNTRY_STR "Индия"
#define Indonesia_COUNTRY_STR "Индонезия"
#define INMARSAT_COUNTRY_STR "INMARSAT"
#define INMARSAT_Atlantic_East_COUNTRY_STR "INMARSAT Atlantic-East"
#define Iran_COUNTRY_STR "Иран"
#define Iraq_COUNTRY_STR "Ирак"
#define Ireland_COUNTRY_STR "Ирландия"
#define Israel_COUNTRY_STR "Израиль"
#define Italy_COUNTRY_STR "Италия"
#define Ivory_Coast_COUNTRY_STR "Ivory Coast"
#define Japan_COUNTRY_STR "Япония"
#define Jordan_COUNTRY_STR "Jordan"
#define Kenya_COUNTRY_STR "Kenya"
#define South_Korea_COUNTRY_STR "Южная Корея"
#define Kuwait_COUNTRY_STR "Кувейт"
#define Liberia_COUNTRY_STR "Либерия"
#define Libya_COUNTRY_STR "Ливия"
#define Liechtenstein_COUNTRY_STR "Liechtenstein"
#define Luxembourg_COUNTRY_STR "Люксембург"
#define Malawi_COUNTRY_STR "Malawi"
#define Malaysia_COUNTRY_STR "Малайзия"
#define Mali_COUNTRY_STR "Мали"
#define Malta_COUNTRY_STR "Мальта"
#define Mexico_COUNTRY_STR "Мексика"
#define Monaco_COUNTRY_STR "Монако"
#define Morocco_COUNTRY_STR "Морокко"
#define Namibia_COUNTRY_STR "Namibia"
#define Nepal_COUNTRY_STR "Непал"
#define Netherlands_COUNTRY_STR "Нидерланды"
#define Netherlands_Antilles_COUNTRY_STR "Netherlands Antilles"
#define New_Caledonia_COUNTRY_STR "New Caledonia"
#define New_Zealand_COUNTRY_STR "Новая Зеландия"
#define Nicaragua_COUNTRY_STR "Никарагуа"
#define Nigeria_COUNTRY_STR "Нигерия"
#define Norway_COUNTRY_STR "Норвегия"
#define Oman_COUNTRY_STR "Oman"
#define Pakistan_COUNTRY_STR "Пакистан"
#define Panama_COUNTRY_STR "Панама"
#define Papua_New_Guinea_COUNTRY_STR "Папуа Новая Гвинея"
#define Paraguay_COUNTRY_STR "Парагвай"
#define Peru_COUNTRY_STR "Перу"
#define Philippines_COUNTRY_STR "Филиппины"
#define Poland_COUNTRY_STR "Польша"
#define Portugal_COUNTRY_STR "Португалия"
#define Qatar_COUNTRY_STR "Qatar"
#define Romania_COUNTRY_STR "Румыния"
#define Russia_COUNTRY_STR "Российская Федерация"
#define Saipan_COUNTRY_STR "Saipan"
#define San_Marino_COUNTRY_STR "Сан Марино"
#define Saudia_Arabia_COUNTRY_STR "Саудовская Арабия"
#define Senegal_COUNTRY_STR "Сенегал"
#define Singapore_COUNTRY_STR "Сингапур"
#define Slovakia_COUNTRY_STR "Словакия"
#define South_Africa_COUNTRY_STR "Южная Африка"
#define Spain_COUNTRY_STR "Испания"
#define Sri_Lanka_COUNTRY_STR "Шри Ланка"
#define Suriname_COUNTRY_STR "Suriname"
#define Sweden_COUNTRY_STR "Швеция"
#define Switzerland_COUNTRY_STR "Switzerland"
#define Taiwan_COUNTRY_STR "Тайвань"
#define Tanzania_COUNTRY_STR "Tanzania"
#define Thailand_COUNTRY_STR "Тайланд"
#define Tunisia_COUNTRY_STR "Tunisia"
#define Turkey_COUNTRY_STR "Турция"
#define United_Arab_Emirates_COUNTRY_STR "Объединенные Арабские Эмираты"
#define Uruguay_COUNTRY_STR "Уругвай"
#define UK_COUNTRY_STR "Объединенное королевство"
#define Ukraine_COUNTRY_STR "Украина"
#define Vatican_City_COUNTRY_STR "Ватикан"
#define Venezuela_COUNTRY_STR "Венесуэлла"
#define Vietnam_COUNTRY_STR "Вьетнам"
#define Yemen_COUNTRY_STR "Yemen"
#define Yugoslavia_COUNTRY_STR "Югославия"
#define Zaire_COUNTRY_STR "Zaire"
#define Zimbabwe_COUNTRY_STR "Зимбабве"
#define NON_COUNTRY_FUNNY_STR "Нелегал"
#define NON_COUNTRY_STR "БОМЖ :("

